### ISSUE TITLE
Add non-standard endpoint details to documentation

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#114]
When using the discovery document at `.well-known/openid-configuration` to configure and OIDC client, the default IdentityServer4 endpoints will be returned, however the VC Identity Provider uses endpoints with the prefix `/vc/`: this should be documented better as it has tripped a few users.

If it is possible to consolidate the endpoints so hat the standard naming convention is respected it would also be great, but I am not sure whether that is possible.

**Comment by esune** [comment]
I cannot recall what was the reason, likely the fact that not all the endpoints could be implemented since vc-authn only deals with authentication, not authorization, and therefore the "standard" endpoints would return out-of-spec responses and be misleading.

**Comment by MonolithicMonk** [comment]
It is an interesting implementation because the current implementation also return misleading endpoints because it uses the standard configuration path - `/.well-known/openid-configuration`.

It would appear that a prefix to the configuration path with `vc` then including `/'vc'` in the path of all the returned endpoints would be sufficient.

**Comment by esune** [comment]
Yes, I agree that a clean-up would be helpful. This would be something to keep in mind for future updates of the platform (e.g.: when moving away from IdentityServer4, which I believe is reaching end of support - https://github.com/bcgov/vc-authn-oidc/issues/171).
