### ISSUE TITLE
Potential for port 5000 conflict on MacOS

### ISSUE THREAD

**Issue by watkinspd** [bcgov/vc-authn-oidc#145]
Suggest updating documentation to warn MacOS users that port 5000 may be in use by AirReceiver, and need to disable that in the control center option for "sharing". 
https://developer.apple.com/forums/thread/682332

**Comment by esune** [comment]
I think I will just leave the ticket here as reference: the issue is not with `vc-authn`, but rather with Apple using ports that have been used for development for a long time out of the blue. There is no guarantee this will not change again in the future, or that they will randomly start using other ports that are already being used by other tools and we don't want to have to maintain a "port list" document here.

**Comment by swcurran** [comment]
I'll add a note to the README.  Mac is a pretty common platform, so lots of people are going to run into this.

While I understand this is a slippery slope, is there any reason not to avoid just 5000 specifically because of this, since it could impact a lot of devs?

**Comment by ianco** [comment]
I ran into this a few weeks ago (I think on the aries vcr demo issuer repo) and I just changed the port from 5000 to 5001

**Comment by swcurran** [comment]
Sounds good.  I'll do a PR to change the default to use something other than 5000 vs. documenting it.

**Comment by swcurran** [comment]
And we can look at how this might affect our many other repos...  :-).  No promises on an immediate fix.

**Comment by WadeBarnes** [comment]
According to this there is a lot of unofficial use of port 5000; https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

**Comment by ianco** [comment]
As an aside, the unit tests for the Java API used by BPA uses a Java library that manages containers and ports - https://www.testcontainers.org/features/networking/

You start up your containers using this framework and it maps the exposed ports to a random free port, you can then use this port to communicate with your container from the unit test.  Pretty slick.

Maybe we need something similar, some way to pick some free ports (in the `manage` script) and then let the user know what ports are being used.

**Comment by esune** [comment]
> According to this there is a lot of unofficial use of port 5000; https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

I still think it is NOT our issue. Otherwise we have to document every potential conflict case regardless of whether it is on MAC, Windows or Linux - for ALL of our repositories. If someone has an issue they can search through the Github issues and find this that will lead them in the right direction.

**Comment by esune** [comment]
> As an aside, the unit tests for the Java API used by BPA uses a Java library that manages containers and ports - https://www.testcontainers.org/features/networking/
> 
> You start up your containers using this framework and it maps the exposed ports to a random free port, you can then use this port to communicate with your container from the unit test. Pretty slick.
> 
> Maybe we need something similar, some way to pick some free ports (in the `manage` script) and then let the user know what ports are being used.

It sounds cool, however in the case of `vc-authn` as well as other apps the chosen ports need to be known since there are child configurations that depend on them (e.g.: webapps or Keycloak must know which port the `vc-authn` controller is listening on).

**Comment by swcurran** [comment]
Closed with #150
