### ISSUE TITLE
Demo not working on Play with Docker

### ISSUE THREAD

**Issue by swcurran** [bcgov/vc-authn-oidc#149]
Trying to run the demo on Play With Docker and finding it is not working. I get an error `{"error":"invalid_redirect_uri"}`. 
 The api is running (e.g. if I got to the equivalent to port 5000 I get the Swagger screen.

Confirmed that things are working fine on local.  I'll see if I can figure anything out further.

Other Notes:

When I tried today on "Play With Docker" itself, I got a "Out of disk space" error in building the images, and so was not able to continue there.  I think that is a temporary error on that service, but we'll see.  On Play with VON everything seemed to start, I ran with the "5001" branch that I used and then tried a new instance with the current main (port 5000) and got the same result.

**Comment by esune** [comment]
I cannot remember how the demo works on PWD/PWV, but `vc-authn` requires clients to be registered with it and have the appropriate redirect URIs in order to successfully complete the auth requests.

The default clients registered for the demo are [here](https://github.com/bcgov/vc-authn-oidc/blob/main/oidc-controller/src/VCAuthn/appsettings.json#L13-L34) and they are based on running the system on localhost. IF the client you are running is on a PWD/PWV url authentication will fail. You would have to add the (dynamic) PWD/PWV url to the client list, which can be done (example in this [manage](https://github.com/bcgov/a2a-trust-over-ip-configurations/blob/main/openshift/manage#L407-L471) script).
