### ISSUE TITLE
"Error: Unknown Presentation Record ID" after clicking Verified Credential Access on Keycloak

### ISSUE THREAD

**Issue by michaeldboyd** [bcgov/vc-authn-oidc#16]
After navigating to keycloak and clicking on the `Verified Credential Access`, I am taken to the VCAuth service and given this message:
`{"error":"unknown_presentation_record_id","error_description":"Cannot find respective record id"}`

I get this error running both the `./manage` script and the manual build with docker. 

I've uploaded the log messages from this call:

I wonder if I need to configure the ledger? Seems that the genesis transaction file is not found.

[log.txt](https://github.com/bcgov/vc-authn-oidc/files/3798775/log.txt)

**Comment by esune** [comment]
@michaeldboyd that error usually happens when the OIDC proof configuration was not set, or the id doesn't match what the OIDC controller is expecting.

The Keycloak login URL contains a query parameter named `pres_req_conf_id` that is currently set to `test-request-config`. The readme makes you setup a proof named 'test` so that won't match the existing configuration. I'll double check the Keycloak config and readme files so that things match, sorry for the confusion.

**Comment by michaeldboyd** [comment]
So if I change the `test` to `test-request-config` it should work? 

Thanks for the help

**Comment by esune** [comment]
Yup, that's it. I updated the readme so that it provides correct instructions ( see #17).

Thanks for catching that!
