### ISSUE TITLE
Consider improvements to the presentation of the "human version" of the proof request

### ISSUE THREAD

**Issue by swcurran** [bcgov/vc-authn-oidc#37]
Suggestion for cleanup of the "What's being asked for" - 

- Get rid "claim" everywhere.
- Collapse the triplet into "Source Credential"
- Make the DID a link that on click pops up the DID
  - could put a link to resolve the DID on the popup.
- Put an "OR" between the triplets. 

Something like:

```
Field: email
Restrictions:
 - Source Credential: verified-email:1.2.2 DID -OR-
 - Source Credential: iiw_attendance:1.2.4 DID -OR-
 - Source Credential: verified_person:1.22 DID
```

Would have to handle things like no restrictions, restrictions by schema, restrictions by cred def, restrictions by name, restrictions by value, etc.

**Comment by swcurran** [comment]
@jljordan42 Please revise the ideas here so that we can have a dev look at this. Or just close it as not needed.

**Comment by esune** [comment]
Wil re-assess as part of the 2.0 development. My first thought is that the current syntax allows for a wide variety of configurations in a language that is similar to what aca-py expects - therefore we do not need to "translate" it when generating the proof-request payload.

A slightly different approach might be to have a (potentially) separate project that could provide "proof composer" functionality and generate the payload to be submitted to vc-authn for the configuration.

**Comment by esune** [comment]
@swcurran I am reviewing this as it has become stale. I think based on the direction we are currently moving towards this might now be somewthing we want in vc-authn anymore, since the proof-requests will potentially be handled elsewhere by a "composer" and then put into the vc-authn database (i.e.: no point in putting effort into coming up with another meta-language to describe the proof-requests). Thoughts?

**Comment by swcurran** [comment]
Sounds good.  I agree that it is not for this component to provide that.
