### ISSUE TITLE
Update UI on rejected proof-request

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#374]
When a proof-request generated by VC-AuthN is rejected (i.e.: the users selects to decline sharing the credentials), the webpage sits at the QR Code page without user feedback.

We should implement a mechanism to:
- detect the proof-request was declined - a problem report should be triggered by the BC Wallet and received by the VC-AuthN agent
- update the UI accordingly, providing a way to start-over

**Comment by esune** [comment]
Small tweak required in ACA-Py for this to work, see https://github.com/hyperledger/aries-cloudagent-python/issues/2597

**Comment by sgroh** [comment]
Hi @esune, @popkinj I had a look to https://github.com/hyperledger/aries-cloudagent-python/issues/2597 and seems an issue already closed, so that means that updating `aries-cloudagent-python` to some version is enough to solve the issue here? 
Or should we also wait for some change on `vc-authn-oidc` project to have this [error](https://github.com/bcgov/vc-authn-oidc/issues/381) solved?

**Comment by popkinj** [comment]
It was determined that the [aries](https://github.com/hyperledger/aries-cloudagent-python) instance isn't capable of sending an error report or denial status for non-connected proofs.

**Comment by esune** [comment]
> It was determined that the [aries](https://github.com/hyperledger/aries-cloudagent-python) instance isn't capable of sending an error report or denial status for non-connected proofs.

I think I have some ideas we can chat about, but they will need changes to aca-py to handle this scenario... Still 🤔

**Comment by loneil** [comment]
Linked PR
https://github.com/bcgov/vc-authn-oidc/pull/406
