### ISSUE TITLE
Scanning QR Code with a regular camera app takes user to a dead end

### ISSUE THREAD

**Issue by cvarjao** [bcgov/vc-authn-oidc#383]
After scanning a QR Code using the built-in camera app, the user has an option to open the URL, and they are instructed to use a digital wallet.
Can we convert that URL to a `bcwallet://` or `didcomm://` protocol and let the user tap to open wallet?

**Comment by esune** [comment]
Are iOS/Android able to handle the handler with a registered application? I thought it was not supported...
And what would happen if the user does NOT have a wallet installed?

**Comment by cvarjao** [comment]
TBD. Just a suggestion. Kim can work on the details on how we can guide users. Something like "I have a wallet ... Click here to open" ... "I don't have a wallet, click here to install". Future improvement

**Comment by esune** [comment]
Recapping the conversations happening in #572:

* When scanning the QR code with the phone camera app, the user will be taken to BC Wallet - if they have it installed.
* If BC Wallet is not installed, the user will be taken to [this page](https://www.figma.com/design/8OzWNqLpmh9M9nR0ynTTTh/VC-AuthN?m=dev&node-id=0-1) from @knguyenBC's mockup.
* There will be no button to open BC Wallet in the "no wallet" page, since the user will be installing the app and have another window open on a separate device with the QR coed to be scanned.
