### ISSUE TITLE
Increasing agent wallet size

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#499]
In our production instance, we have seen the agent wallet size increase steadily. At a first glance, it looks like exchange records might be preserved (i.e.: trying to fetch presentation exchange records via the API yields a timeout), but this should not be the case since the agent is supposed to delete exchange records once they have been completed.

**Comment by Gavinok** [comment]
Here are my current findings and each step taken


# Check if we are storing records

using `GET /present-proof/records` from the swagger ui in the vc-authn agent we can see that each request even when verified sticks around

```json
{
  "results": [
    {
      "state": "request_sent",
...
    },
    {
      "state": "request_sent",
...
     },
    {
      "state": "request_sent",
...
   }
  ]
}
```

-   We are definitely storing the records even after verification
-   I ensured that we are both not passing the env var `ACAPY_PRESERVE_EXCHANGE_RECORDS` or the cli arg `--preserve-exchange-records` to acapy


# Run demo and check if records are stored

I needed to comment out the passing of `--preserve-exchange-records` in <https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/runners/support/agent.py#L516> to replicate the vc-authn setup.

after executing Issue Credential followed by

-   `GET /present-proof/records` results in

```json-ts
{
  "results": []
}
```

Using v0.1 however v0.2 seems to have some output but its only one result at a time

`GET /present-proof-2.0/records` only displayed one request sent at a time meaning that verified proof will be discarded.


# Test the current demo version of acapy

The current acapy demo does delete out of band proof requests records. However, this is using the 2.0 proof request API

Since the demo is using the latest acapy version I also tested vc-authn after updating the acapy version.


# Test vc-authn with latest acapy version


## With Update to ACAPY version 3.9-0.12.0rc0 -> 3.9-0.12.1

```diff
diff --git a/docker/docker-compose.yaml b/docker/docker-compose.yaml
index 7aa2d0a..90d7f59 100644
--- a/docker/docker-compose.yaml
+++ b/docker/docker-compose.yaml
@@ -95,7 +95,7 @@ services:
       - vc_auth

   aca-py:
-    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.12.0rc0
+    image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.12.1
     environment:
       - ACAPY_LABEL=${AGENT_NAME}
       - ACAPY_ENDPOINT=${AGENT_ENDPOINT}
```

After 2 qr requests and 2 successes (total of 4 proof requests)

This is the results of the 1.0 `GET /present-proof/records`

```json
{
  "results": [
    {
      "state": "verified",
      "created_at": "2024-05-08T19:03:38.394369Z",
      "updated_at": "2024-05-08T19:03:50.706993Z",
      "trace": false,
      ...
    },
    {
      "state": "verified",
      "created_at": "2024-05-08T19:04:22.724160Z",
      "updated_at": "2024-05-08T19:04:32.862763Z",
      "trace": false,
      ...
    },
    {
      "state": "request_sent",
      "created_at": "2024-05-08T19:02:22.520866Z",
      "updated_at": "2024-05-08T19:02:22.520866Z",
      "trace": false,
      ...
    },
    {
      "state": "request_sent",
      "created_at": "2024-05-08T19:03:22.566061Z",
      "updated_at": "2024-05-08T19:03:22.566061Z",
      "trace": false,
      ...
    }
  ]
}
```

This gives 2 proof requests (qr refreshes) and verified proof requests

Indicating that even with the latest acapy version we still are recording logs when using the 1.0 api


# What Does this all mean

-   Records are not deleted when using the 1.0 api (bug in acapy)
-   Sent requests are kept around every QR code refresh (bug in vc-authn)
-   vc-authn should update to the 2.0 proof request API

**Comment by esune** [comment]
Will be partially tackled in #424, to be re-assessed after #512
