### ISSUE TITLE
Investigate effort/approach to using vc-authn-oidc with Slack

### ISSUE THREAD

**Issue by swcurran** [bcgov/vc-authn-oidc#56]
See the [Slack OAuth 2.0 API](https://api.slack.com/docs/oauth).  Investigate using vc-authn-oidc with that and figure out how it can be used:

- who would host the VC containers?
- how would the proof request get defined?
- What is the configuration flow?
- What docs would be helpful to support this to enable fast deployment and scale?

**Comment by swcurran** [comment]
FYI @jljordan42 and @watkinspd

**Comment by esune** [comment]
Newer docs: https://api.slack.com/authentication/oauth-v2

**Comment by esune** [comment]
As far as I can tell, the only way to sign-in to slack is to either use a Slack account, or a SAML IdP as described here: https://slack.com/intl/en-ca/help/articles/203772216-SAML-single-sign-on

The documents we were initially looking at (older and updated) describe how to provide access to a Slack app (e.g.: a bot) to the workspace using Slack's own OAuh 2.0 identity provider: the app requests access to the Slack API using a confidential OIDC client/secret combination, similarly to what a backend service does with Keycloak.

If I understand correctly, the use-case we're trying to solve is - instead - providing real users with access to Slack by authenticating using a Verifiable Credential. @swcurran can you please confirm?

_At this time only these scenarios are possible:_
- sign-in to Slack using a third party SAML Identity Provider. This requires the IdP to be configured inside the slack workspace.
- access a slack workspace using Slack's in-house OAuth 2 Identity Provider: this is the scenario described above for a Slack app.

For Slack to be able to use vc-auth as Identity Provider means that vc-authn would have to be SAML-compatible (basically write a brand new IdP module). Then it could be configured for each of the workspaces requiring it for user authentication.

_Notes:_
- vc-authn could be hosted anywhere (e.g.: in OpenShift like we already do) as it is a third-party service that only needs to be interfaced with Slack
- the proof request configuration would likely need to include a unique field for each user, in order to bind it to the user profile: similarly to what we are experiencing in Keycloak, the fact that vc-authn does not provide a unique identifier when authenticating is a challenge as it will be impossible to reconcile different user logins with the same user.
  - a way to work around this would be to map the user email provided by the credential as unique user identifier. Users would always have to authenticate using the same email address in order to access their session/profile. What happens if a user needs to change the email address for some reason?

**Comment by swcurran** [comment]
Thanks, @esune.

- Confirmed that the use case we are after is authenticating to get access to a Slack workspace using a VC.
- The SAML effort is kind of what I was expecting.  We'd have to build `vc-authn-saml` using the same architecture, but a different library to handle the SAML side of the interaction.
- I would argue that it is not `vc-authn-oidc` that defines whether or not there is a unique field to use or not - it's the credential, how we want to use the credential, and the proof request.
   - In the Services Card case with Keycloak, we do have a unique ID for the credential, we just don't want to use it for the Keycloak use cases.
   - That said, we really want to have a unique ID per combination of service+credential as there is for OIDC.  There is not a way to do that currently and that is something we want to look into.

Do those comments make sense, or did I miss something in my reading of your comments?

**Comment by esune** [comment]
Yes, comments make sense thanks @swcurran. Are we then looking at estimating the effort to build a SAML version of `vc-authn`, or were we just trying to figure out if that was the case? I would need to see what's out there that could help us build the service.

Regarding `vc-authn` and the unique field: OIDC considers the `sub` field as the unique identifier for the user that is authenticating, and `vc-authn` always generates a new `sub` for each authentication request since there is no user data that is stored on the controller that can be used to reconcile who is requesting access.

We can definitely use a combination of one or more claims as unique identifier for the user, but this requires the application consuming the token (whether it is Keycloak, Slack or something else) to implement some logic to parse that and use it as identifier instead of the `sub` field (I think this should be possible with Keycloak by using mappers, not 100% sure though).
I do not know ( at least not yet) how SAML works, but I assume that something similar would have to be considered for this implementation as well.

**Comment by esune** [comment]
Resources for SAML stacks: https://medium.com/the-new-control-plane/i-need-a-saml-stack-now-63d9691e2d43

**Comment by esune** [comment]
List of SAML stacks that could be possibly used to implenent a new service: https://medium.com/the-new-control-plane/i-need-a-saml-stack-now-63d9691e2d43

**Comment by jljordan42** [comment]
Keycloak has SAML built in ... we would just front those services with KeyCloak I should think

**Comment by esune** [comment]
@jljordan42 unfortunately I don't think that will work: Slack acts as Identity Broker and interfacing with one or more SAML Identity Providers, similarly to what Keycloak does for us with GitHub, IDIR, vc-auth.
Keycloak can't act as SAML Identity Provider and be consumed by other services - I believe it only exposes an OIDC interface.

**Comment by andrewwhitehead** [comment]
> We can definitely use a combination of one or more claims as unique identifier for the user, but this requires the application consuming the token (whether it is Keycloak, Slack or something else) to implement some logic to parse that and use it as identifier instead of the sub field (I think this should be possible with Keycloak by using mappers, not 100% sure though).

I feel like this has to be defined as part of the mapping, not implemented at the application level for each consumer. Maybe it could generate a hash of some specific claims if configured, or all claims otherwise.

**Comment by swcurran** [comment]
I agree that it should be in the mapping.  I want to talk to Mike L about what is/could be possible in this scenario.

**Comment by esune** [comment]
@swcurran @andrewwhitehead that's my thought as well. It is easy to get the mapping right when using Keycloak as far as I'm concerned, but I'm not sure about other identity brokers such as Slack.

If an app is consuming vc-authn directly then having the appropriate claims will do, since the app will just manage the mappings internally.

**Comment by NickDarvey** [comment]
I'm not sure if Slack does SAML2P or WS-Fed, but given what you already have, is this an option? http://www.identityserver.com/articles/saml-20-integration-with-identityserver4

**Comment by esune** [comment]
Thanks @NickDarvey for the resource, that seems to be an option we could look into to potentially add SAML2 support to the existing implementation.
